### ISSUE TITLE
Something In The Way She Moves by The Beatles

### ISSUE THREAD

**Issue by WoutGroenendijk** [schuifel-shuffle/data#20]
Remastered edition:
https://open.spotify.com/track/7oSUp4yZ0FbuSvVmCxH2ty

@cecilevdwaal 
@rvanlaarhoven 
@luukjanssens

**Comment by rvanlaarhoven** [comment]
Hmm, I actually can't imagine schuifelen on this track.. Especially the part around 1:20...

**Comment by WoutGroenendijk** [comment]
Declined
