### ISSUE TITLE
Classic hit missing from the list

### ISSUE THREAD

**Issue by cecilevdwaal** [schuifel-shuffle/data#27]
https://open.spotify.com/track/3V0PeMg2mhbYRtk9bioAwF?si=ymwgeYJJTTW1qE0RIbGfXg 

Had my Spotify on shuffle (of course) and this song came by. Can't believe this classic song is not in the list yet!

**Comment by WoutGroenendijk** [comment]
How did this not make the list yet?!! I'm shuffling in my mind already just by listening to it. 

@rvanlaarhoven We deserve answers because this is outrages!

**Comment by rvanlaarhoven** [comment]
Haha sounds familiar somewhere, but to be honest I don't really know this one. Good one though 😄

**Comment by rvanlaarhoven** [comment]
Ok, I couldn't just comment. I had to `Close and comment`...
