### ISSUE TITLE
Change request: Imagine by John Lennon

### ISSUE THREAD

**Issue by cecilevdwaal** [schuifel-shuffle/data#5]
I would like to request a change in the playlist. This version is merely a piano version of John Lennon's image: https://open.spotify.com/track/7tLxZQX2tO9GxtyKQF6PuL?si=23lTe9d_TbuytV-E4agTaw, which is currently in the list. 

My request is to change it for Spotify's remastered version: https://open.spotify.com/track/7pKfPomDEeI4TPT6EOYjn9?si=WfkuOR-pTOeqbGDFsinnZA

**Comment by rvanlaarhoven** [comment]
I actually also noticed that piano version and couldn't remember ever adding it to the playlist. Probably I just dragged in the incorrect version
